// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfHwM413RocJRIO43Jaosd8aC4FzwZYOw',
    appId: '1:484166768436:web:4b1bf34a3cc2cd57583761',
    messagingSenderId: '484166768436',
    projectId: 'flutter-auth-app-3ece3',
    authDomain: 'flutter-auth-app-3ece3.firebaseapp.com',
    storageBucket: 'flutter-auth-app-3ece3.firebasestorage.app',
    measurementId: 'G-PH0SCD09JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_0xwEbCKNHXJ_RMAefzdUf7pnRZpustM',
    appId: '1:484166768436:android:974e5fa49214c2bb583761',
    messagingSenderId: '484166768436',
    projectId: 'flutter-auth-app-3ece3',
    storageBucket: 'flutter-auth-app-3ece3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgbkeqYo5gTFuiKcT7rzscQyLDjIKvKA',
    appId: '1:484166768436:ios:20306ffdebdb8f7a583761',
    messagingSenderId: '484166768436',
    projectId: 'flutter-auth-app-3ece3',
    storageBucket: 'flutter-auth-app-3ece3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgbkeqYo5gTFuiKcT7rzscQyLDjIKvKA',
    appId: '1:484166768436:ios:20306ffdebdb8f7a583761',
    messagingSenderId: '484166768436',
    projectId: 'flutter-auth-app-3ece3',
    storageBucket: 'flutter-auth-app-3ece3.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfHwM413RocJRIO43Jaosd8aC4FzwZYOw',
    appId: '1:484166768436:web:e64b31e56725e779583761',
    messagingSenderId: '484166768436',
    projectId: 'flutter-auth-app-3ece3',
    authDomain: 'flutter-auth-app-3ece3.firebaseapp.com',
    storageBucket: 'flutter-auth-app-3ece3.firebasestorage.app',
    measurementId: 'G-BZ9KJWR031',
  );
}
